# Generated by Django 3.2.19 on 2023-06-29 15:27

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('category', models.CharField(choices=[('Traditional', 'Traditional'), ('Neo Traditional', 'Neo Traditional'), ('Fine Line', 'Fine Line'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Japanese', 'Japanese'), ('Patchwork', 'Patchwork'), ('Ignorant', 'Ignorant'), ('Portrait', 'Portrait'), ('Animal', 'Animal'), ('Floral', 'Floral')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appointment_at', models.DateTimeField()),
                ('tattoo_location', models.CharField(blank=True, choices=[('Ear', 'Ear'), ('Neck', 'Neck'), ('Shoudler', 'Shoulder'), ('Bicep', 'Bicep'), ('Forearm', 'Forearm'), ('Arm', 'Arm'), ('Chest', 'Chest'), ('Sternum', 'Sternum'), ('Stomach', 'Stomach'), ('Hip', 'Hip'), ('Thigh', 'Thigh'), ('Knee', 'Knee'), ('Calf', 'Calf'), ('Shin', 'Shin'), ('Ankle', 'Ankle'), ('Foot', 'Foot')], max_length=30, null=True)),
                ('tattoo_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-large')], max_length=3)),
                ('tattoo_category', models.CharField(blank=True, choices=[('Traditional', 'Traditional'), ('Neo Traditional', 'Neo Traditional'), ('Fine Line', 'Fine Line'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Japanese', 'Japanese'), ('Patchwork', 'Patchwork'), ('Ignorant', 'Ignorant'), ('Portrait', 'Portrait'), ('Animal', 'Animal'), ('Floral', 'Floral')], max_length=30, null=True)),
                ('comment', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_artist', to='core.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', 'artist'],
            },
        ),
    ]
