# Generated by Django 3.2.19 on 2023-07-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230629_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
    ]
