# Generated by Django 3.2.19 on 2023-07-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Nonbinary', 'Nonbinary'), ('Other', 'Other')], max_length=10),
        ),
    ]
