# Generated by Django 3.2.19 on 2023-07-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artist_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_artist', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
