# Generated by Django 3.2.19 on 2023-07-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230706_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tattoo_category',
            field=models.CharField(blank=True, choices=[('Neo Traditional', 'Neo Traditional'), ('Fine Line', 'Fine Line'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Japanese', 'Japanese'), ('Patchwork', 'Patchwork'), ('Ignorant', 'Ignorant'), ('Portrait', 'Portrait'), ('Animal', 'Animal'), ('Floral', 'Floral')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='skills',
            field=models.CharField(blank=True, choices=[('Neo Traditional', 'Neo Traditional'), ('Fine Line', 'Fine Line'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Japanese', 'Japanese'), ('Patchwork', 'Patchwork'), ('Ignorant', 'Ignorant'), ('Portrait', 'Portrait'), ('Animal', 'Animal'), ('Floral', 'Floral')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('Neo Traditional', 'Neo Traditional'), ('Fine Line', 'Fine Line'), ('Tribal', 'Tribal'), ('Watercolor', 'Watercolor'), ('Blackwork', 'Blackwork'), ('Realism', 'Realism'), ('Japanese', 'Japanese'), ('Patchwork', 'Patchwork'), ('Ignorant', 'Ignorant'), ('Portrait', 'Portrait'), ('Animal', 'Animal'), ('Floral', 'Floral')], max_length=100),
        ),
    ]
