# Generated by Django 3.2.19 on 2023-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='featured_image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
